package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// build bundles src/index.js into a QML-loadable ESM bundle, verifies every
// manifest entry point exists, and generates ui/<Name>.qml (the reactive
// bridge QtObject) from the plugin's state({...}) exports. Bundle and bridge
// share ui/ because Quickshell's script loader cannot resolve ../ imports,
// and qmldir singletons don't run Component.onCompleted.
func build(dir string) error {
	start := time.Now()
	res, err := runBuild(dir)
	if err != nil {
		return err
	}
	okLine(fmt.Sprintf("%s  %s", res.bundleRel, humanSize(res.bundleBytes)))
	if res.bridgeRel != "" {
		okLine(res.bridgeRel)
	}
	doneLine("built", time.Since(start))
	if needsInstall(dir) {
		nextHint("oma install")
	}
	return nil
}

// buildResult describes what one build produced, so command wrappers can
// report artifacts without the package flow printing them twice.
type buildResult struct {
	bundleRel   string // "ui/index.mjs"
	bundleBytes int64
	bridgeRel   string // "ui/<Name>.qml", "" if none was generated
}

// runBuild performs the full build silently; output belongs to the wrappers
// ('oma build' summarizes, 'oma package' stays quiet about this stage).
func runBuild(dir string) (buildResult, error) {
	res := buildResult{bundleRel: filepath.ToSlash(filepath.Join("ui", "index.mjs"))}
	if err := bundleProject(dir); err != nil {
		return res, err
	}
	if err := ensureLauncherService(dir); err != nil {
		return res, fmt.Errorf("launcher service: %w", err)
	}
	if err := validateEntryPoints(dir); err != nil {
		return res, err
	}
	bridge, err := generateBridge(dir)
	if err != nil {
		return res, err
	}
	res.bridgeRel = bridge
	if info, err := os.Stat(filepath.Join(dir, "ui", "index.mjs")); err == nil {
		res.bundleBytes = info.Size()
	}
	return res, nil
}

// needsInstall reports whether the installed copy is missing or older than
// the fresh bundle — i.e. whether the summary should suggest 'oma install'.
func needsInstall(dir string) bool {
	dest, err := pluginDest(dir)
	if err != nil {
		return false
	}
	if _, err := os.Stat(dest); os.IsNotExist(err) {
		return true
	}
	return installedStale(
		filepath.Join(dir, "ui", "index.mjs"),
		filepath.Join(dest, "ui", "index.mjs"),
	)
}

func validateEntryPoints(dir string) error {
	m, err := readManifest(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return err
	}
	for key, rel := range m.EntryPoints {
		if _, err := os.Stat(filepath.Join(dir, filepath.FromSlash(rel))); err != nil {
			return fmt.Errorf("entry point %q -> %q is missing", key, rel)
		}
	}
	return nil
}

// bridgeBaseName returns the capitalized, QML-safe bridge name for a plugin,
// appending "Bridge" when it would collide with a surface file name (a plugin
// named "Panel" with a panel kind would otherwise fight ui/Panel.qml).
// Single source of truth for build, surface add, scaffold and status.
func bridgeBaseName(name string, kinds []string) string {
	base := qmlSafeBridge(name)
	for _, k := range kinds {
		if qmlName[k] == base+".qml" {
			base += "Bridge"
			break
		}
	}
	return base
}

// generateBridge scans src/index.js for state({...}) exports and functions
// and emits ui/<Name>.qml, the reactive QtObject that surfaces consume. It
// imports index.mjs from the same directory (Quickshell cannot resolve ../
// script imports). Returns the written file relative to the project dir.
func generateBridge(dir string) (string, error) {
	m, err := readManifest(filepath.Join(dir, "manifest.json"))
	if err != nil {
		return "", err
	}
	// checked against the raw name: qmlSafeBridge never returns empty (it
	// falls back to "Bridge"), so a name-less manifest must not slip through
	if strings.TrimSpace(m.Name) == "" {
		return "", fmt.Errorf("manifest has no name")
	}
	name := bridgeBaseName(capitalize(m.Name), m.Kinds)
	// belt & braces: never clobber an existing ui file that isn't our own bridge
	for i := 0; i < 4; i++ {
		p := filepath.Join(dir, "ui", name+".qml")
		data, err := os.ReadFile(p)
		if err != nil || strings.Contains(string(data), "// Generated by oma build") {
			break // free (or our previous bridge - safe to regenerate)
		}
		name += "Bridge"
	}
	srcPath := entryPoint(dir)
	if srcPath == "" {
		return "", fmt.Errorf("missing src/index.js or src/index.ts")
	}
	src, err := os.ReadFile(srcPath)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", srcPath, err)
	}
	meta, notes, err := scanBridge(string(src))
	for _, n := range notes.ignored {
		fmt.Fprintln(os.Stderr, "oma:", n)
	}
	if err != nil {
		return "", fmt.Errorf("bridge scan: %w", err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "ui"), 0o755); err != nil {
		return "", err
	}
	out := filepath.Join(dir, "ui", name+".qml")
	content := "// Generated by oma build - do not edit.\n" + renderBridge(meta, "index.mjs", m.ID) + "\n"
	if err := writeFile(out, content); err != nil {
		return "", err
	}
	return filepath.ToSlash(filepath.Join("ui", name+".qml")), nil
}

func readManifest(path string) (manifest, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return manifest{}, fmt.Errorf("read manifest: %w", err)
	}
	var m manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return manifest{}, fmt.Errorf("parse manifest: %w", err)
	}
	return m, nil
}

// ensureLauncherService auto-creates a service that writes launcher entries
// when oma.json launchers[] is non-empty. Generated files are regenerated on
// every build; a custom Service.qml is never touched - oma only writes the
// LauncherWriter.qml helper and tells the dev to instantiate it.
func ensureLauncherService(dir string) error {
	cfg, err := loadOMAConfig(dir)
	if err != nil {
		// broken oma.json is reported elsewhere; don't block build
		return nil
	}
	if len(cfg.Launchers) == 0 {
		return nil
	}
	mPath := filepath.Join(dir, "manifest.json")
	m, err := readManifest(mPath)
	if err != nil {
		return nil
	}

	var entries []struct{ Filename, Content string }
	for i, def := range cfg.Launchers {
		fn, content := renderLauncherEntry(m, def, cfg.Icon, i, dir, true)
		entries = append(entries, struct{ Filename, Content string }{fn, content})
	}
	if len(entries) == 0 {
		return nil
	}
	writer := launcherWriterSkeleton(m.ID, entries)

	helperQml := filepath.Join(dir, "ui", "LauncherWriter.qml")
	serviceQml := filepath.Join(dir, "ui", "Service.qml")

	if _, err := os.Stat(serviceQml); err == nil {
		data, _ := os.ReadFile(serviceQml)
		if !strings.Contains(string(data), launcherWriterMarker) {
			// custom service: write helper, let the dev wire it in
			if err := writeFile(helperQml, writer); err != nil {
				return err
			}
			fmt.Fprintf(os.Stderr, "warning: Service.qml is custom - add LauncherWriter {} to it for auto-created entries (see ui/LauncherWriter.qml)\n")
			return nil
		}
	} else {
		if err := writeFile(serviceQml, launcherServiceSkeleton(m.ID)); err != nil {
			return err
		}
		if !contains(m.Kinds, "service") {
			m.Kinds = append(m.Kinds, "service")
		}
		if m.EntryPoints == nil {
			m.EntryPoints = map[string]string{}
		}
		m.EntryPoints["service"] = "ui/Service.qml"
		if err := writeJSON(mPath, m); err != nil {
			return err
		}
		okLine("added service (launcher entries need a writer)")
	}
	return writeFile(helperQml, writer)
}
