package main

import (
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"
)

// runDev watches the project for changes and runs build -> install -> shell
// restart on every edit. A hidden panel's surface is destroyed (not just
// hidden), so Quickshell's per-plugin hot reload cannot pick up surface
// changes - a full shell restart is the only dependable refresh. Polling
// (~500ms) beats an fsnotify dependency for a dev loop.
func runDev(dir string) error {
	if _, err := readManifest(filepath.Join(dir, "manifest.json")); err != nil {
		return fmt.Errorf("not an oma project: %w", err)
	}

	okLine("watching " + dir + " (Ctrl-C to stop)")
	noteLine("edit src/, ui/, manifest.json or oma.json - changes are built, installed and the shell restarted")

	last := snapshotModTimes(dir)
	tick := time.NewTicker(500 * time.Millisecond)
	defer tick.Stop()

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, os.Interrupt, syscall.SIGTERM)
	defer signal.Stop(sig)

	for {
		select {
		case <-sig:
			fmt.Println()
			noteLine("stopped watching")
			return nil
		case <-tick.C:
			cur := snapshotModTimes(dir)
			if sameSnapshot(last, cur) {
				continue
			}
			last = cur
			noteLine("change detected - building")
			if err := build(dir); err != nil {
				fmt.Fprintln(os.Stderr, "error:", err)
				noteLine("build failed - waiting for the next edit")
				last = snapshotModTimes(dir) // edits during the failed build
				continue
			}
			if err := restart(dir); err != nil {
				fmt.Fprintln(os.Stderr, "error:", err)
				noteLine("install/restart failed - waiting for the next edit")
				last = snapshotModTimes(dir)
				continue
			}
			okLine("watching again")
			last = snapshotModTimes(dir) // absorb artifacts the build just wrote
		}
	}
}

// snapshotModTimes records mtimes of everything that shapes a build, skipping
// generated artifacts (the bundle and anything stamped "Generated by oma
// build") so the loop does not retrigger on its own output.
func snapshotModTimes(dir string) map[string]time.Time {
	out := map[string]time.Time{}
	walk := func(root string) {
		_ = filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
			if err != nil || info.IsDir() || generatedArtifact(path) {
				return nil
			}
			out[path] = info.ModTime()
			return nil
		})
	}
	walk(filepath.Join(dir, "src"))
	walk(filepath.Join(dir, "ui"))
	for _, f := range []string{"manifest.json", "oma.json"} {
		if info, err := os.Stat(filepath.Join(dir, f)); err == nil {
			out[filepath.Join(dir, f)] = info.ModTime()
		}
	}
	return out
}

// generatedArtifact reports whether a file is build output rather than
// hand-written source: the bundle, or anything stamped by the generator.
func generatedArtifact(path string) bool {
	if filepath.Base(path) == "index.mjs" {
		return true
	}
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer f.Close()
	head := make([]byte, 120)
	n, _ := f.Read(head)
	return strings.Contains(string(head[:n]), "Generated by oma build")
}

func sameSnapshot(a, b map[string]time.Time) bool {
	if len(a) != len(b) {
		return false
	}
	for k, va := range a {
		vb, ok := b[k]
		if !ok || !va.Equal(vb) {
			return false
		}
	}
	return true
}
