package main

import (
	"io"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// captureStdout swaps os.Stdout while fn runs and returns what it printed.
func captureStdout(t *testing.T, fn func()) string {
	t.Helper()
	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	fn()
	w.Close()
	os.Stdout = old
	data, err := io.ReadAll(r)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}

// writeMinProject scaffolds the minimum files runStatus needs: a manifest
// whose name collides with its panel surface, a src file and ui artifacts.
func writeMinProject(t *testing.T) string {
	t.Helper()
	dir := t.TempDir()
	m := manifest{
		SchemaVersion: 1,
		ID:            "t.panel",
		Name:          "Panel",
		Version:       "0.1.0",
		Kinds:         []string{"panel"},
		EntryPoints:   map[string]string{"panel": "ui/Panel.qml"},
	}
	if err := writeJSON(filepath.Join(dir, "manifest.json"), m); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(dir, "src"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "src", "index.js"), []byte("export {};\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	return dir
}

// Regression: status used to freshness-check ui/Panel.qml (the surface)
// instead of the collision-renamed bridge. With only the surface present,
// the build verdict must be "not built yet", not stale/fresh.
func TestStatusUsesRenamedBridge(t *testing.T) {
	dir := writeMinProject(t)
	if err := os.MkdirAll(filepath.Join(dir, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	// surface skeleton exists; the generated PanelBridge.qml does not
	if err := os.WriteFile(filepath.Join(dir, "ui", "Panel.qml"), []byte("Panel {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	out := stripCodes(captureStdout(t, func() { _ = runStatus(dir) }))
	if !strings.Contains(out, "not built yet") {
		t.Fatalf("expected missing-bridge verdict, got:\n%s", out)
	}

	// once the renamed bridge exists, verdict flips to stale: buildStale
	// needs both artifacts and compares against src + config file mtimes,
	// so make src the clearly newer side
	bridge := filepath.Join(dir, "ui", "PanelBridge.qml")
	if err := os.WriteFile(bridge, []byte("// Generated by oma build\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	bundle := filepath.Join(dir, "ui", "index.mjs")
	if err := os.WriteFile(bundle, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	future := time.Now().Add(time.Hour)
	src := filepath.Join(dir, "src", "index.js")
	if err := os.Chtimes(src, future, future); err != nil {
		t.Fatal(err)
	}
	out = stripCodes(captureStdout(t, func() { _ = runStatus(dir) }))
	if !strings.Contains(out, "stale") || strings.Contains(out, "not built yet") {
		t.Fatalf("expected stale verdict against the renamed bridge, got:\n%s", out)
	}
}

// A half-deleted install must not read as fresh: needsInstall hints when the
// installed bundle is missing, older, or absent — but not when up to date.
func TestNeedsInstallStates(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := writeMinProject(t)

	if !needsInstall(dir) {
		t.Fatal("uninstalled project should hint install")
	}

	dest := filepath.Join(home, ".config", "omarchy", "plugins", "t.panel")
	if err := os.MkdirAll(filepath.Join(dest, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dest, "ui", "index.mjs"), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	// no local bundle yet -> nothing to compare, no hint
	if needsInstall(dir) {
		t.Fatal("no local bundle should not hint install")
	}

	// local bundle newer than installed copy -> hint
	if err := os.MkdirAll(filepath.Join(dir, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	local := filepath.Join(dir, "ui", "index.mjs")
	if err := os.WriteFile(local, []byte("newer"), 0o644); err != nil {
		t.Fatal(err)
	}
	future := time.Now().Add(time.Hour)
	if err := os.Chtimes(local, future, future); err != nil {
		t.Fatal(err)
	}
	if !needsInstall(dir) {
		t.Fatal("stale installed copy should hint install")
	}

	// installed bundle deleted in place -> still hint (was silently fresh)
	if err := os.Remove(filepath.Join(dest, "ui", "index.mjs")); err != nil {
		t.Fatal(err)
	}
	if !needsInstall(dir) {
		t.Fatal("missing installed bundle should hint install")
	}
}

// installedStale: local missing dominates (nothing to compare), installed
// missing counts as stale when the local artifact exists.
func TestInstalledStaleMissing(t *testing.T) {
	a := filepath.Join(t.TempDir(), "a.mjs")
	b := filepath.Join(t.TempDir(), "b.mjs")
	if err := os.WriteFile(a, []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	if installedStale(a, b) != true {
		t.Error("missing installed artifact should read as stale")
	}
	if installedStale(b, a) != false {
		t.Error("missing local artifact cannot be compared")
	}
}

// The installed line must distinguish not-installed, incomplete and stale.
func TestStatusInstalledVariants(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := writeMinProject(t)
	dest := filepath.Join(home, ".config", "omarchy", "plugins", "t.panel")

	status := func() string {
		return stripCodes(captureStdout(t, func() { _ = runStatus(dir) }))
	}

	if out := status(); !strings.Contains(out, "not installed (oma install)") {
		t.Fatalf("missing not-installed line:\n%s", out)
	}

	// incomplete: plugin dir exists but the bundle is missing
	if err := os.MkdirAll(filepath.Join(dest, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	if out := status(); !strings.Contains(out, "incomplete install") {
		t.Fatalf("missing incomplete-install line:\n%s", out)
	}

	// fresh: both artifacts present, installed not older than local
	if err := os.MkdirAll(filepath.Join(dir, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	for _, p := range []string{filepath.Join(dir, "ui", "index.mjs"), filepath.Join(dest, "ui", "index.mjs")} {
		if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	out := status()
	if strings.Contains(out, "incomplete install") || strings.Contains(out, "older than local build") {
		t.Fatalf("fresh install misread:\n%s", out)
	}
	if !strings.Contains(out, dest) {
		t.Fatalf("installed path not shown:\n%s", out)
	}

	// stale: local bundle newer than the installed one
	future := time.Now().Add(time.Hour)
	if err := os.Chtimes(filepath.Join(dir, "ui", "index.mjs"), future, future); err != nil {
		t.Fatal(err)
	}
	if out := status(); !strings.Contains(out, "older than local build") {
		t.Fatalf("missing stale line:\n%s", out)
	}
}

// Both-mode panels surface the extra PanelWindow.qml line (not an entryPoint).
func TestStatusPanelWindowLine(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if err := os.MkdirAll(filepath.Join(project, "ui"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := writeJSON(filepath.Join(project, "manifest.json"), manifest{
		SchemaVersion: 1,
		ID:            "t.p",
		Name:          "P",
		Version:       "0.1.0",
		Kinds:         []string{"bar-widget", "panel"},
		EntryPoints:   map[string]string{"barWidget": "ui/BarWidget.qml", "panel": "ui/PanelWindow.qml"},
	}); err != nil {
		t.Fatal(err)
	}
	writeOMAConfig(t, project, `{"panel":{"mode":"both"}}`)
	for _, f := range []string{"ui/BarWidget.qml", "ui/PanelWindow.qml", "src/index.js"} {
		full := filepath.Join(project, f)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte("x"), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	out := stripCodes(captureStdout(t, func() { _ = runStatus(project) }))
	if !strings.Contains(out, "panel-window → ui/PanelWindow.qml") {
		t.Fatalf("missing panel-window line:\n%s", out)
	}
	if !strings.Contains(out, "panel") {
		t.Fatalf("missing panel mode line:\n%s", out)
	}
}

// Launcher state: not-created, created, and broken-config paths.
func TestStatusLauncherLines(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	dir := writeMinProject(t)
	writeOMAConfig(t, dir, `{"launchers":[{"name":"App"}]}`)

	status := func() string {
		return stripCodes(captureStdout(t, func() { _ = runStatus(dir) }))
	}

	if out := status(); !strings.Contains(out, "not created") {
		t.Fatalf("missing not-created line:\n%s", out)
	}

	if _, err := writeLauncherEntries(dir); err != nil {
		t.Fatal(err)
	}
	out := status()
	if strings.Contains(out, "not created") {
		t.Fatalf("created entry still reported missing:\n%s", out)
	}
	if !strings.Contains(out, "t.panel.desktop") {
		t.Fatalf("launcher path not shown:\n%s", out)
	}

	writeOMAConfig(t, dir, `{broken`)
	if out := status(); !strings.Contains(out, "parse oma.json") {
		t.Fatalf("broken config not surfaced:\n%s", out)
	}
}

// The editor-lib line reflects the installed @oma/runtime version vs the CLI.
func TestStatusLibVersionLine(t *testing.T) {
	dir := writeMinProject(t)
	libPkg := filepath.Join(dir, "node_modules", "@oma", "runtime", "package.json")
	if err := os.MkdirAll(filepath.Dir(libPkg), 0o755); err != nil {
		t.Fatal(err)
	}
	status := func() string {
		return stripCodes(captureStdout(t, func() { _ = runStatus(dir) }))
	}

	if out := status(); !strings.Contains(out, "not installed (optional") {
		t.Fatalf("missing lib-not-installed line:\n%s", out)
	}

	if err := os.WriteFile(libPkg, []byte(`{"version":"9.9.9"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	out := status()
	if !strings.Contains(out, "@oma/runtime 9.9.9") || !strings.Contains(out, "cli is "+version()) {
		t.Fatalf("missing version-drift line:\n%s", out)
	}

	if err := os.WriteFile(libPkg, []byte(`{"version":"`+version()+`"}`), 0o644); err != nil {
		t.Fatal(err)
	}
	if out := status(); !strings.Contains(out, "@oma/runtime "+version()) || strings.Contains(out, "cli is") {
		t.Fatalf("matching version misread:\n%s", out)
	}
}
