package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const buildFixtureSrc = `import { config, state } from "@oma/runtime";

export const music = state({
  playing: false,
  song: "",
  volume: 100,
});

export const settings = config({ volume: 80 });

export function toggle() {
  music.playing = !music.playing;
}

export function setVolume(v) {
  music.volume = Number(v);
}
`

// The full build pipeline runs in-process (esbuild is embedded), so it must be
// covered hermetically: bundle, launcher-service check, entry-point validation
// and bridge generation.
func TestBuildEndToEnd(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "mybuild")
	if _, err := scaffoldWithOptions(project, []string{"bar-widget"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(project, "src", "index.js"), []byte(buildFixtureSrc), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := runBuild(project)
	if err != nil {
		t.Fatal(err)
	}
	if res.bundleRel != "ui/index.mjs" {
		t.Fatalf("bundleRel = %q", res.bundleRel)
	}
	if res.bridgeRel != "ui/Mybuild.qml" {
		t.Fatalf("bridgeRel = %q", res.bridgeRel)
	}

	// bundle: ESM output, runtime inlined via the @oma/runtime alias, wrapper
	// re-exporting the persistence bootstrap
	bundle, err := os.ReadFile(filepath.Join(project, "ui", "index.mjs"))
	if err != nil {
		t.Fatal(err)
	}
	bs := string(bundle)
	for _, want := range []string{"function state(", "__omaBindRef", "function toggle"} {
		if !strings.Contains(bs, want) {
			t.Errorf("bundle missing %q", want)
		}
	}
	if strings.Contains(bs, "@oma/runtime") {
		t.Error("bundle still references the @oma/runtime specifier (alias not resolved)")
	}

	// bridge: reactive properties per state field, delegating methods, sync
	// loop and the persistence bootstrap
	bridge, err := os.ReadFile(filepath.Join(project, "ui", "Mybuild.qml"))
	if err != nil {
		t.Fatal(err)
	}
	qs := string(bridge)
	for _, want := range []string{
		`import "index.mjs" as Logic`,
		"property bool playing",
		"property string song",
		"property double volume",
		"function toggle() { return Logic.toggle.apply(null, arguments) }",
		"function setVolume() { return Logic.setVolume.apply(null, arguments) }",
		"root.playing = Logic.music.playing",
		"Logic.music.subscribe(apply0)",
		"Logic.__omaBindRef(saved, root.__omaPersist)",
		".config/omarchy/tester.mybuild.json",
	} {
		if !strings.Contains(qs, want) {
			t.Errorf("bridge missing %q", want)
		}
	}
}

// A manifest entry point pointing at a missing file must fail the build.
func TestBuildEntryPointMissing(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if err := os.MkdirAll(filepath.Join(project, "src"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := writeJSON(filepath.Join(project, "manifest.json"), manifest{
		SchemaVersion: 1,
		ID:            "t.p",
		Name:          "P",
		Version:       "0.1.0",
		Kinds:         []string{"overlay"},
		EntryPoints:   map[string]string{"overlay": "ui/Missing.qml"},
	}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(project, "src", "index.js"), []byte("export {}\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := runBuild(project); err == nil || !strings.Contains(err.Error(), "entry point") {
		t.Fatalf("expected missing-entry-point error, got %v", err)
	}
}

// A project whose bridge name collides with a surface file must get the
// collision-renamed bridge (belt-and-braces path in generateBridge).
func TestBuildBridgeCollision(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "Panel")
	if _, err := scaffoldWithOptions(project, []string{"panel"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(project, "src", "index.js"), []byte(buildFixtureSrc), 0o644); err != nil {
		t.Fatal(err)
	}

	res, err := runBuild(project)
	if err != nil {
		t.Fatal(err)
	}
	if res.bridgeRel != "ui/PanelBridge.qml" {
		t.Fatalf("bridgeRel = %q, want ui/PanelBridge.qml (surface collision)", res.bridgeRel)
	}
	if _, err := os.Stat(filepath.Join(project, "ui", "PanelBridge.qml")); err != nil {
		t.Fatal(err)
	}
	// the surface skeleton is never clobbered
	surface, err := os.ReadFile(filepath.Join(project, "ui", "Panel.qml"))
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(surface), "// Generated by oma build") {
		t.Fatal("surface Panel.qml was overwritten by the bridge")
	}

	// rebuilding regenerates the renamed bridge, not a second variant
	res, err = runBuild(project)
	if err != nil {
		t.Fatal(err)
	}
	if res.bridgeRel != "ui/PanelBridge.qml" {
		t.Fatalf("second build moved the bridge to %q", res.bridgeRel)
	}
}

// --- ensureLauncherService ---

// No launchers declared: nothing is created, the manifest is untouched.
func TestLauncherServiceNoLaunchers(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if _, err := scaffoldWithOptions(project, []string{"panel"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	if err := ensureLauncherService(project); err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{"ui/Service.qml", "ui/LauncherWriter.qml"} {
		if _, err := os.Stat(filepath.Join(project, f)); !os.IsNotExist(err) {
			t.Fatalf("%s created without launchers", f)
		}
	}
}

// Launchers declared + no Service.qml: the stub service is created, registered
// in the manifest and paired with the writer helper.
func TestLauncherServiceCreatesStub(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if _, err := scaffoldWithOptions(project, []string{"panel"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	writeOMAConfig(t, project, `{"launchers":[{"name":"App","action":"toggle"}]}`)

	if err := ensureLauncherService(project); err != nil {
		t.Fatal(err)
	}

	stub, err := os.ReadFile(filepath.Join(project, "ui", "Service.qml"))
	if err != nil {
		t.Fatal(err)
	}
	ss := string(stub)
	if !strings.Contains(ss, launcherWriterMarker) || !strings.Contains(ss, "LauncherWriter {}") {
		t.Fatalf("stub service missing marker or writer instantiation:\n%s", ss)
	}

	helper, err := os.ReadFile(filepath.Join(project, "ui", "LauncherWriter.qml"))
	if err != nil {
		t.Fatal(err)
	}
	hs := string(helper)
	for _, want := range []string{launcherWriterMarker, "tester.p.desktop", "bash"} {
		if !strings.Contains(hs, want) {
			t.Errorf("LauncherWriter missing %q", want)
		}
	}

	m, err := readManifest(filepath.Join(project, "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !contains(m.Kinds, "service") || m.EntryPoints["service"] != "ui/Service.qml" {
		t.Fatalf("manifest not registered: kinds=%v entryPoints=%v", m.Kinds, m.EntryPoints)
	}
}

// A custom (marker-less) Service.qml is preserved; only the helper is written
// and the manifest is not touched.
func TestLauncherServiceCustomKept(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if _, err := scaffoldWithOptions(project, []string{"panel"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	writeOMAConfig(t, project, `{"launchers":[{"name":"App"}]}`)
	custom := "import QtQuick\nItem { id: root }\n"
	if err := os.WriteFile(filepath.Join(project, "ui", "Service.qml"), []byte(custom), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := ensureLauncherService(project); err != nil {
		t.Fatal(err)
	}

	got, err := os.ReadFile(filepath.Join(project, "ui", "Service.qml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != custom {
		t.Fatalf("custom Service.qml was modified:\n%s", got)
	}
	if _, err := os.Stat(filepath.Join(project, "ui", "LauncherWriter.qml")); err != nil {
		t.Fatal("helper not written for custom service")
	}
	m, _ := readManifest(filepath.Join(project, "manifest.json"))
	if contains(m.Kinds, "service") {
		t.Fatalf("custom service caused manifest registration: %v", m.Kinds)
	}
}

// Re-running over the generated stub regenerates the helper without
// duplicating the service kind.
func TestLauncherServiceRegeneration(t *testing.T) {
	dir := t.TempDir()
	project := filepath.Join(dir, "p")
	if _, err := scaffoldWithOptions(project, []string{"panel"}, scaffoldOptions{Author: "tester"}); err != nil {
		t.Fatal(err)
	}
	writeOMAConfig(t, project, `{"launchers":[{"name":"App"}]}`)
	if err := ensureLauncherService(project); err != nil {
		t.Fatal(err)
	}
	if err := ensureLauncherService(project); err != nil {
		t.Fatal(err)
	}

	m, err := readManifest(filepath.Join(project, "manifest.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !contains(m.Kinds, "service") {
		t.Fatalf("service kind lost on regeneration: %v", m.Kinds)
	}
	if strings.Count(strings.Join(m.Kinds, ","), "service") != 1 {
		t.Fatalf("service kind duplicated: %v", m.Kinds)
	}
	if _, err := os.Stat(filepath.Join(project, "ui", "LauncherWriter.qml")); err != nil {
		t.Fatal("helper missing after regeneration")
	}
}
