// Generated by oma build - do not edit.
import QtQuick
import Quickshell
import Quickshell.Io
import "index.mjs" as Logic

QtObject {
  id: root

  property var unsubscribers: []
  property double count
  property double step
  function applySavedStep() { return Logic.applySavedStep.apply(null, arguments) }
  function inc() { return Logic.inc.apply(null, arguments) }
  function dec() { return Logic.dec.apply(null, arguments) }
  function reset() { return Logic.reset.apply(null, arguments) }
  function setStep() { return Logic.setStep.apply(null, arguments) }

  // Persistence: config() stores survive restarts via ~/.config/omarchy/examples.counter.json.
  readonly property string omaHome: Quickshell.env("HOME")
  property bool omaBound: false
  property var omaData: null

  function __omaPersist(data) {
    root.omaData = data
    omaSaveTimer.restart()
  }

  function __omaLoad(raw) {
    if (root.omaBound) return
    var saved = {}
    try { saved = JSON.parse(String(raw || "{}")) } catch (e) {}
    Logic.__omaBindRef(saved, root.__omaPersist)
    root.omaBound = true
  }

  property FileView omaSettingsFile: FileView {
    path: root.omaHome + "/.config/omarchy/examples.counter.json"
    watchChanges: false
    atomicWrites: true
    printErrors: false
    onLoaded: root.__omaLoad(text())
    onLoadFailed: root.__omaLoad("")
  }

  // Debounced like other omarchy plugins; a slider dragging across set()
  // calls would otherwise hit the disk on every tick.
  property Timer omaSaveTimer: Timer {
    interval: 200
    onTriggered: omaSettingsFile.setText(JSON.stringify(root.omaData, null, 2) + "\n")
  }

  Component.onCompleted: {
    var apply0 = function() {
        root.count = Logic.counter.count
        root.step = Logic.counter.step
    }
    apply0()
    unsubscribers.push(Logic.counter.subscribe(apply0))
  }

  Component.onDestruction: {
    for (var i = 0; i < unsubscribers.length; i++) unsubscribers[i]()
  }
}
