// Generated by oma build - do not edit.
import QtQuick
import Quickshell
import Quickshell.Io
import "index.mjs" as Logic

QtObject {
  id: root

  property var unsubscribers: []
  property string open
  property string done
  function add() { return Logic.add.apply(null, arguments) }
  function complete() { return Logic.complete.apply(null, arguments) }
  function reopen() { return Logic.reopen.apply(null, arguments) }
  function clearDone() { return Logic.clearDone.apply(null, arguments) }

  // Persistence: config() stores survive restarts via ~/.config/omarchy/examples.todo.json.
  // The runtime re-targets its write channel on every bind and buffers
  // writes while no bridge is alive, so surface churn (panel hide/show,
  // registry rescans) cannot lose data. `omaReady` flips once seeding
  // completed; reads before that see defaults, writes before it are
  // buffered and win over the disk seed.
  readonly property string omaHome: Quickshell.env("HOME")
  property bool omaReady: false
  property var omaData: null
  property var omaSink: null

  function __omaPersist(data) {
    root.omaData = data
    omaSaveTimer.restart()
  }

  function __omaLoad(raw) {
    if (root.omaReady) return
    var saved = {}
    try { saved = JSON.parse(String(raw || "{}")) } catch (e) {}
    root.omaSink = Logic.__omaBindRef(saved, root.__omaPersist)
    root.omaReady = true
  }

  property FileView omaSettingsFile: FileView {
    path: root.omaHome + "/.config/omarchy/examples.todo.json"
    watchChanges: false
    atomicWrites: true
    printErrors: false
    onLoaded: root.__omaLoad(text())
    onLoadFailed: root.__omaLoad("")
  }

  // Debounced like other omarchy plugins; a slider dragging across set()
  // calls would otherwise hit the disk on every tick. The runtime exposes
  // the interval so config({ debounceMs }) can override it.
  property Timer omaSaveTimer: Timer {
    interval: Logic.__omaDebounceMsRef()
    onTriggered: omaSettingsFile.setText(JSON.stringify(root.omaData, null, 2) + "\n")
  }

  Component.onCompleted: {
    var apply0 = function() {
        root.open = Logic.__omaSnap(Logic.todos.open)
        root.done = Logic.__omaSnap(Logic.todos.done)
    }
    apply0()
    unsubscribers.push(Logic.todos.subscribe(apply0))
  }

  Component.onDestruction: {
    for (var i = 0; i < unsubscribers.length; i++) unsubscribers[i]()
    if (root.omaData !== null && omaSaveTimer.running)
      omaSettingsFile.setText(JSON.stringify(root.omaData, null, 2) + "\n")
    Logic.__omaUnbindRef(root.omaSink)
  }
}
