// Generated by oma build - do not edit.
import QtQuick
import Quickshell
import Quickshell.Io
import "index.mjs" as Logic

QtObject {
  id: root

  property var unsubscribers: []
  property bool running
  property double seconds
  property string display
  property double tickMs
  property string lastEvent
  function tick() { return Logic.tick.apply(null, arguments) }
  function start() { return Logic.start.apply(null, arguments) }
  function stop() { return Logic.stop.apply(null, arguments) }
  function toggle() { return Logic.toggle.apply(null, arguments) }
  function reset() { return Logic.reset.apply(null, arguments) }
  function resetViaIpc() { return Logic.resetViaIpc.apply(null, arguments) }
  function setTickMs() { return Logic.setTickMs.apply(null, arguments) }
  function getTitle() { return Logic.getTitle.apply(null, arguments) }
  function getTickCount() { return Logic.getTickCount.apply(null, arguments) }

  // Persistence: config() stores survive restarts via ~/.config/omarchy/examples.stopwatch.json.
  // The runtime re-targets its write channel on every bind and buffers
  // writes while no bridge is alive, so surface churn (panel hide/show,
  // registry rescans) cannot lose data. `omaReady` flips once seeding
  // completed; reads before that see defaults, writes before it are
  // buffered and win over the disk seed.
  readonly property string omaHome: Quickshell.env("HOME")
  property bool omaReady: false
  property var omaData: null
  property var omaSink: null

  function __omaPersist(data) {
    root.omaData = data
    omaSaveTimer.restart()
  }

  function __omaLoad(raw) {
    if (root.omaReady) return
    var saved = {}
    try { saved = JSON.parse(String(raw || "{}")) } catch (e) {}
    root.omaSink = Logic.__omaBindRef(saved, root.__omaPersist)
    root.omaReady = true
  }

  property FileView omaSettingsFile: FileView {
    path: root.omaHome + "/.config/omarchy/examples.stopwatch.json"
    watchChanges: false
    atomicWrites: true
    printErrors: false
    onLoaded: root.__omaLoad(text())
    onLoadFailed: root.__omaLoad("")
  }

  // Debounced like other omarchy plugins; a slider dragging across set()
  // calls would otherwise hit the disk on every tick. The runtime exposes
  // the interval so config({ debounceMs }) can override it.
  property Timer omaSaveTimer: Timer {
    interval: Logic.__omaDebounceMsRef()
    onTriggered: omaSettingsFile.setText(JSON.stringify(root.omaData, null, 2) + "\n")
  }

  Component.onCompleted: {
    var apply0 = function() {
        root.running = Logic.__omaSnap(Logic.timer.running)
        root.seconds = Logic.__omaSnap(Logic.timer.seconds)
        root.display = Logic.__omaSnap(Logic.timer.display)
        root.tickMs = Logic.__omaSnap(Logic.timer.tickMs)
        root.lastEvent = Logic.__omaSnap(Logic.timer.lastEvent)
    }
    apply0()
    unsubscribers.push(Logic.timer.subscribe(apply0))
  }

  Component.onDestruction: {
    for (var i = 0; i < unsubscribers.length; i++) unsubscribers[i]()
    if (root.omaData !== null && omaSaveTimer.running)
      omaSettingsFile.setText(JSON.stringify(root.omaData, null, 2) + "\n")
    Logic.__omaUnbindRef(root.omaSink)
  }
}
